language: node_js

node_js:
  - 8
  - 10
  - 12
  - lts/*

os:
  - linux
  - osx
  - windows

cache: npm

install:
  - npm install

git:
  quiet: true
  depth: 1

script:
  - npm test
  - npm run build

before_script:
  - npm install mocha rollup @babel/register -g

after_success:
  - npm run test:coveralls