language: node_js

node_js:
  - 8
  - 10
  - 12
  - latest

os:
  - linux
  - osx
  - windows

cache: npm

install:
  - npm install

branches:
  only:
    - master

git:
  quiet: true
  depth: 1

script:
  - npm test:coverage
  - npm run build

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"