language: node_js

node_js:
  - 8
  - 10
  - 12
  - latest

os:
  - linux
  - osx
  - windows

cache: npm

install:
  - npm install

branches:
  only:
    - master

git:
  quiet: true
  depth: 1

script:
  - npm test
  - npm run build

after_success:
  - npm run test:coveralls